import type { Metadata } from "next";
import { Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";
import Layouts from "@/components/layouts";
import NextAuthProvider from "@/components/layouts/Auth/NextAuthProvider";

export const roboto = Roboto({
    subsets: ["latin"],
    weight: "100",
});

const playfair = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${playfair.className}`}>
                <NextAuthProvider>
                    <Layouts>{children}</Layouts>
                </NextAuthProvider>
            </body>
        </html>
    );
}
